### ISSUE TITLE
network docker-compose config error when run.sh

### ISSUE THREAD

**Issue by einsteinarbert** [dev-m00n/ambari-local-cluster#4]
ERROR: The Compose file './docker-compose.yml' is invalid because:
networks.cluster-network.ipam.config value Additional properties are not allowed ('gateway' was unexpected)

> maybe wrong Ip addr config

**Comment by dev-m00n** [comment]
@einsteinarbert sorry actually I don't maintain this anymore. The reason that I no longer do it is because resource requirement is quite(Cluster is up and eventually down) a lot as well as need many effort to run ambari cluster on local.
But let me look into it when I feel free, sorry for late reply
